<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Cubic Zirconia Price Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Project_1_files/libs/clipboard/clipboard.min.js"></script>
<script src="Project_1_files/libs/quarto-html/quarto.js"></script>
<script src="Project_1_files/libs/quarto-html/popper.min.js"></script>
<script src="Project_1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Project_1_files/libs/quarto-html/anchor.min.js"></script>
<link href="Project_1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Project_1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Project_1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Project_1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Project_1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cubic Zirconia Price Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The goal of this analysis is to explore the relationships between cubic zirconia gemstone characteristics (e.g., <code>carat</code>, <code>cut</code>, <code>color</code>, <code>clarity</code>) and price. The analysis emphasizes inference, focusing on identifying significant predictors and understanding their relationships while ensuring statistical rigor.</p>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'

The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'gridExtra'

The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
</div>
</section>
<section id="load-the-dataset" class="level1">
<h1>Load the dataset</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>path <span class="ot">&lt;-</span> <span class="st">"cubic_zirconia.csv"</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> path, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
Rows: 26967 Columns: 11
── Column specification
──────────────────────────────────────────────────────── Delimiter: "," chr
(3): cut, color, clarity dbl (8): ...1, carat, depth, table, x, y, z, price
ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
Specify the column types or set `show_col_types = FALSE` to quiet this message.
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
   ...1 carat cut       color clarity depth table     x     y     z price
  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1  0.3  Ideal     E     SI1      62.1    58  4.27  4.29  2.66   499
2     2  0.33 Premium   G     IF       60.8    58  4.42  4.46  2.7    984
3     3  0.9  Very Good E     VVS2     62.2    60  6.04  6.12  3.78  6289
4     4  0.42 Ideal     F     VS1      61.6    56  4.82  4.8   2.96  1082
5     5  0.31 Ideal     F     VVS1     60.4    59  4.35  4.43  2.65   779
6     6  1.02 Ideal     D     VS2      61.5    56  6.46  6.49  3.99  9502</code></pre>
</div>
</div>
<p>Response Variable:</p>
<pre><code>Price : the Price of the cubic zirconia.</code></pre>
<p>Possible Covariates:</p>
<pre><code>Carat : Carat weight of the cubic zirconia.

Cut : Describe the cut quality of the cubic zirconia. Quality is increasing order Fair, Good, Very Good, Premium, Ideal.

Color: Colour of the cubic zirconia.With D being the best and J the worst.

Clarity : cubic zirconia Clarity refers to the absence of the Inclusions and Blemishes. (In order from Best to Worst, FL = flawless, I3= level 3 inclusions) - FL, IF, VVS1, VVS2, VS1, VS2, SI1, SI2, I1, I2, I3

Depth : The Height of a cubic zirconia, measured from the Culet to the table, divided by its average Girdle Diameter.

Table : The Width of the cubic zirconia's Table expressed as a percentage of its Average Diameter.

X : Length of the cubic zirconia in mm.

Y : Width of the cubic zirconia in mm.

Z : Height of the cubic zirconia in mm.</code></pre>
</section>
<section id="clean-the-dataset" class="level1">
<h1>Clean the dataset</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Removing row count column</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 10
  carat cut       color clarity depth table     x     y     z price
  &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  0.3  Ideal     E     SI1      62.1    58  4.27  4.29  2.66   499
2  0.33 Premium   G     IF       60.8    58  4.42  4.46  2.7    984
3  0.9  Very Good E     VVS2     62.2    60  6.04  6.12  3.78  6289
4  0.42 Ideal     F     VS1      61.6    56  4.82  4.8   2.96  1082
5  0.31 Ideal     F     VVS1     60.4    59  4.35  4.43  2.65   779
6  1.02 Ideal     D     VS2      61.5    56  6.46  6.49  3.99  9502</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis-eda" class="level1">
<h1>Exploratory Data Analysis (EDA)</h1>
<section id="summary-statistics" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics">Summary Statistics</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">str_glue</span> (<span class="st">"There are {nrow(data)} rows in the dataset.</span><span class="sc">\n\n</span><span class="st">"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>There are 26967 rows in the dataset.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">str_glue</span>(<span class="st">"There are {sum(is.na(data))} total missing values in the dataset.</span><span class="sc">\n</span><span class="st"> Total missing values per column:</span><span class="sc">\n\n</span><span class="st">"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>There are 697 total missing values in the dataset.
Total missing values per column:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  carat     cut   color clarity   depth   table       x       y       z   price 
      0       0       0       0     697       0       0       0       0       0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> <span class="fu">drop_na</span>(depth)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  carat     cut   color clarity   depth   table       x       y       z   price 
      0       0       0       0       0       0       0       0       0       0 </code></pre>
</div>
</div>
</section>
</section>
<section id="correcting-column-data-types" class="level1">
<h1>Correcting Column Data Types</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>cut <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>cut, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Ideal"</span>, <span class="st">"Premium"</span>, <span class="st">"Very Good"</span>, <span class="st">"Good"</span>, <span class="st">"Fair"</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>color <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>color, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"D"</span>, <span class="st">"E"</span>, <span class="st">"F"</span>, <span class="st">"G"</span>, <span class="st">"H"</span>, <span class="st">"I"</span>, <span class="st">"J"</span>))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>clarity <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>clarity, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"FL"</span>, <span class="st">"IF"</span>, <span class="st">"VVS1"</span>, <span class="st">"VVS2"</span>, <span class="st">"VS1"</span>, <span class="st">"VS2"</span>, <span class="st">"SI1"</span>, <span class="st">"SI2"</span>, <span class="st">"I1"</span>, <span class="st">"I2"</span>, <span class="st">"I3"</span>))</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 10
  carat cut       color clarity depth table     x     y     z price
  &lt;dbl&gt; &lt;fct&gt;     &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  0.3  Ideal     E     SI1      62.1    58  4.27  4.29  2.66   499
2  0.33 Premium   G     IF       60.8    58  4.42  4.46  2.7    984
3  0.9  Very Good E     VVS2     62.2    60  6.04  6.12  3.78  6289
4  0.42 Ideal     F     VS1      61.6    56  4.82  4.8   2.96  1082
5  0.31 Ideal     F     VVS1     60.4    59  4.35  4.43  2.65   779
6  1.02 Ideal     D     VS2      61.5    56  6.46  6.49  3.99  9502</code></pre>
</div>
</div>
<section id="distributions-of-variables" class="level2">
<h2 class="anchored" data-anchor-id="distributions-of-variables">Distributions of Variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to calculate proportions and create a plot</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>create_proportion_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(var, var_name) {</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  prop_table <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(var)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  prop_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(prop_table)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>(prop_df) <span class="ot">&lt;-</span> <span class="fu">c</span>(var_name, <span class="st">"proportion"</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(prop_df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">get</span>(var_name), <span class="at">y =</span> proportion)) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"purple"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> var_name, <span class="at">y =</span> <span class="st">"Proportion (%)"</span>, <span class="at">title =</span> <span class="fu">str_glue</span>(<span class="st">"Proportion of Categories in {str_to_title(var_name)}"</span>)) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>)) </span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">create_proportion_plot</span>(data<span class="sc">$</span>clarity, <span class="st">"clarity"</span>)</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">create_proportion_plot</span>(data<span class="sc">$</span>cut, <span class="st">"cut"</span>)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">create_proportion_plot</span>(data<span class="sc">$</span>color, <span class="st">"color"</span>)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, p3, <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">widths =</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">8</span>, <span class="dv">8</span>), <span class="at">heights =</span> <span class="fu">c</span>(<span class="dv">8</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The graphs above indicate that the categories within each categorical variable are not equally represented in the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> price)) <span class="sc">+</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">15</span>, <span class="at">fill =</span> <span class="st">"purple"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Price ($)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">title =</span> <span class="st">"Price Distribution"</span>) <span class="sc">+</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">16</span>)) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(price), <span class="at">color =</span> <span class="st">"Mean"</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">median</span>(price), <span class="at">color =</span> <span class="st">"Median"</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Mean"</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"Median"</span> <span class="ot">=</span> <span class="st">"blue"</span>)) <span class="sc">+</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>), <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The above histogram for the response variable, Price, shows a right skewed distribution. The mean is higher than the median.</p>
</section>
<section id="relationships-between-variables" class="level2">
<h2 class="anchored" data-anchor-id="relationships-between-variables">Relationships Between Variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># graphing all continuous variables against price (the response)</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>continuous_vars <span class="ot">=</span> <span class="fu">c</span>(<span class="st">'carat'</span>, <span class="st">'depth'</span>, <span class="st">'table'</span>, <span class="st">'x'</span>, <span class="st">'y'</span>, <span class="st">'z'</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>labels <span class="ot">=</span> <span class="fu">c</span>(<span class="st">'Carat'</span>, <span class="st">'Depth'</span>, <span class="st">'Table (%)'</span>, <span class="st">'Length (mm)'</span>, <span class="st">'Width (mm)'</span>, <span class="st">'Height (mm)'</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>plot_list <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(continuous_vars)) {</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> data, <span class="fu">aes</span>(<span class="at">x =</span> .data[[continuous_vars[i]]], <span class="at">y =</span> price)) <span class="sc">+</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"purple"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>            <span class="fu">labs</span>(<span class="at">x =</span> labels[i], <span class="at">y =</span> <span class="st">"Price ($)"</span>, <span class="at">title =</span> <span class="fu">str_glue</span>(<span class="st">"Price vs {stringr::str_to_title(continuous_vars[i])}"</span>)) <span class="sc">+</span> </span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>            <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    plot_list[[i]] <span class="ot">&lt;-</span> p</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(<span class="at">grobs =</span> plot_list, <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>todo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>cat_vars <span class="ot">=</span> <span class="fu">c</span>(<span class="st">'cut'</span>, <span class="st">'color'</span>, <span class="st">'clarity'</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(cat_vars)) {</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> data, <span class="fu">aes</span>(<span class="at">x =</span> .data[[cat_vars[i]]], <span class="at">y =</span> price, <span class="at">color =</span> .data[[cat_vars[i]]])) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">labs</span>(<span class="at">x =</span> stringr<span class="sc">::</span><span class="fu">str_to_title</span>(cat_vars[i]), <span class="at">y =</span> <span class="st">"Price ($)"</span>, <span class="at">title =</span> <span class="fu">str_glue</span>(<span class="st">"Price vs {stringr::str_to_title(cat_vars[i])}"</span>)) <span class="sc">+</span> </span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>))</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(p)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There appears to be a lot of overlap between boxplots in the cut and color plots. This suggests there might not be a strong relationship between different cut and color categories and price. However, there seems to be less overlap between boxes in the clarity plot. For example, there is almost no overlap between the IF (internally flawless) and I1 (level 1 inclusions) categories. This indicates that clarity may be a stronger predictor of price. This is intuitive because gemstones with higher clarity are generally more expensive. Cut and color may not be as strongly correlated with price.</p>
<p>It is interesting to note that in the third plot of price vs clarity, the median price for IF gemstones is lower than the median price for I1 gemstones. This however, is counterintuitive because a flawless gemstone should have the highest price.</p>
<p>The following graph suggests that the lower price for IF gemstones may have been because of lower weights of such cubic zirconia being bought. This suggests there may be some interaction between weight of the gemstone and its clarity in determining the price of a gemstone.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data, <span class="fu">aes</span>(<span class="at">x =</span> clarity, <span class="at">y =</span> carat, <span class="at">color =</span> clarity)) <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Clarity"</span>, <span class="at">y =</span> <span class="st">"Weight (carat)"</span>, <span class="at">title =</span> <span class="st">"Carat vs Clarity"</span>) <span class="sc">+</span> </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> carat, <span class="at">y =</span> price)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Price vs Carat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Based on the graph above, we assume that the model to be linear (i.e we do not include higher degree term in our model). There is a slight curve in the graph, so we have decided to include the interaction between carat and clarity to introduce some non-linearity.</p>
</section>
</section>
<section id="multicollinearity-analysis" class="level1">
<h1>Multicollinearity Analysis</h1>
<section id="variance-inflation-factor-vif" class="level2">
<h2 class="anchored" data-anchor-id="variance-inflation-factor-vif">Variance Inflation Factor (VIF)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>model_initial <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> carat <span class="sc">+</span> color <span class="sc">+</span> cut <span class="sc">+</span> clarity <span class="sc">+</span> depth <span class="sc">+</span> table <span class="sc">+</span> x <span class="sc">+</span> y <span class="sc">+</span> z, <span class="at">data =</span> data)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>vif_values <span class="ot">&lt;-</span> <span class="fu">vif</span>(model_initial)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vif_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             GVIF Df GVIF^(1/(2*Df))
carat   23.700250  1        4.868290
color    1.177673  6        1.013722
cut      1.943575  4        1.086614
clarity  1.338129  7        1.021023
depth    2.612679  1        1.616378
table    1.811095  1        1.345769
x       94.946811  1        9.744065
y       14.565816  1        3.816519
z       79.093240  1        8.893438</code></pre>
</div>
</div>
<ul>
<li><p><code>carat</code>: <strong>22.79</strong> → Severe multicollinearity.</p></li>
<li><p><code>x</code>, <code>z</code>: <strong>92.71</strong> and <strong>78.46</strong> → Extremely severe multicollinearity.</p></li>
<li><p><code>y</code>: <strong>14.53</strong> → Moderate to severe multicollinearity.</p></li>
<li><p><code>depth</code>: <strong>2.30</strong> and <code>table</code>: <strong>1.14</strong> → These are within acceptable ranges.</p></li>
</ul>
<p>We saw that the VIF for ‘x’, ‘y’, ‘z’ are high. However, ‘x’, ‘y’, ‘z’ measures the dimension of the diamond and one would think these variables to be independent. Therefore, we created a new variable, namely ‘volume’ to address the problem of multicollinearity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>volume <span class="ot">&lt;-</span> data<span class="sc">$</span>x <span class="sc">*</span> data<span class="sc">$</span>y <span class="sc">*</span> data<span class="sc">$</span>z</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>model_with_volume <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> carat <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity <span class="sc">+</span> depth <span class="sc">+</span> table <span class="sc">+</span> volume, <span class="at">data =</span> data)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>vif_with_volume <span class="ot">&lt;-</span> <span class="fu">vif</span>(model_with_volume)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"VIF for Model with Volume:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "VIF for Model with Volume:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vif_with_volume)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             GVIF Df GVIF^(1/(2*Df))
carat   13.356479  1        3.654652
cut      1.920930  4        1.085023
color    1.168104  6        1.013033
clarity  1.290073  7        1.018359
depth    1.392378  1        1.179991
table    1.814473  1        1.347024
volume  12.941611  1        3.597445</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model_without_volume <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> carat <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity <span class="sc">+</span> depth <span class="sc">+</span> table, <span class="at">data =</span> data)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>vif_without_volume <span class="ot">&lt;-</span> <span class="fu">vif</span>(model_without_volume)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"VIF for Model without Volume:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "VIF for Model without Volume:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vif_without_volume)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            GVIF Df GVIF^(1/(2*Df))
carat   1.327111  1        1.152003
cut     1.920649  4        1.085003
color   1.168019  6        1.013027
clarity 1.289804  7        1.018344
depth   1.384640  1        1.176707
table   1.809651  1        1.345233</code></pre>
</div>
</div>
<p>From the above output, we can see that VIF’s for carat and volume are above the general threshold of 5, suggesting multicollinearity.</p>
<ol type="1">
<li><p>We can drop ‘volume’ since it is intuitive to think that ‘carat’ (weight) and ‘volume’ are related. Additionally, ‘carat’ seems more important of a measure for gemstones, as it is more commonly used in practice to measure gemstones. Keeping only <code>carat</code> simplifies the model and avoids redundancy. This is the ideal approach if we wish to retain the interpretability of the model.</p></li>
<li><p>Another thing we can do is we can try using Principle Component Regression to address the multicollinearity between carat and volume. This is a good approach if we only wish to create a high accuracy prediction model and not necessarily retain interpretability.</p></li>
</ol>
</section>
</section>
<section id="outlier-detection" class="level1">
<h1>Outlier Detection</h1>
<p>From the exploratory data analysis, we can see the presence of a lot of outliers. Here, we will address the problem of outliers.</p>
<section id="standardized-residuals" class="level2">
<h2 class="anchored" data-anchor-id="standardized-residuals">Standardized Residuals</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardized residuals</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> carat <span class="sc">+</span> cut <span class="sc">+</span> clarity <span class="sc">+</span> depth <span class="sc">+</span> table, <span class="at">data =</span> data)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>residuals <span class="ot">&lt;-</span> <span class="fu">rstandard</span>(model)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify outliers</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(residuals) <span class="sc">&gt;</span> <span class="dv">3</span>)  <span class="co"># Residuals &gt; 3 standard deviations</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">nrow</span>(outliers))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 586</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(outliers)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 586 × 12
   carat cut       color clarity depth table     x     y     z price volume
   &lt;dbl&gt; &lt;fct&gt;     &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1  1.04 Premium   D     VVS2     61.1    60  6.54  6.51  3.99 10984   170.
 2  1.8  Very Good E     SI1      62.2    57  7.81  7.89  4.88 17273   301.
 3  1.69 Ideal     F     VS2      62.2    57  7.59  7.66  4.74 16789   276.
 4  2.8  Premium   I     SI2      61.1    59  9.03  8.98  5.5  15030   446.
 5  1.71 Ideal     G     VS1      63      56  7.65  7.58  4.8  17009   278.
 6  1.5  Very Good F     VS1      60.5    55  7.39  7.48  4.5  15585   249.
 7  2.11 Premium   E     SI2      62.4    61  8.19  8.1   5.08 18034   337.
 8  1.04 Ideal     D     IF       61.8    57  6.49  6.52  4.02 14494   170.
 9  1.22 Ideal     F     VVS1     61.2    57  6.88  6.92  4.22 13029   201.
10  1.2  Ideal     F     VVS1     61.1    55  6.86  6.89  4.2  13088   199.
# ℹ 576 more rows
# ℹ 1 more variable: residuals &lt;dbl&gt;</code></pre>
</div>
</div>
<p>We can see that we have 586 outliers. This is 586/26967 * 100 ~ 2.17% of our data. Since we are not sure if these outliers are the result of data entry errors, etc, we will not remove the outliers as that may lead to deletion of useful information.</p>
</section>
</section>
<section id="regression-analysis-after-dropping-volume" class="level1">
<h1>Regression Analysis After Dropping Volume</h1>
<section id="stepwise-selection" class="level2">
<h2 class="anchored" data-anchor-id="stepwise-selection">Stepwise Selection</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>predictors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"carat"</span>, <span class="st">"cut"</span>, <span class="st">"color"</span>, <span class="st">"clarity"</span>, <span class="st">"depth"</span>, <span class="st">"table"</span>) </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>response <span class="ot">&lt;-</span> <span class="st">"price"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="fit-initial-and-full-models" class="level1">
<h1>Fit initial and full models</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>simple_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">as.formula</span>(<span class="fu">paste</span>(response, <span class="st">"~ 1"</span>)), <span class="at">data =</span> data)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> carat <span class="sc">*</span> clarity <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> depth <span class="sc">+</span> table, <span class="at">data =</span> data)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>stepwise_model <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(simple_model, <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> simple_model, <span class="at">upper =</span> full_model), <span class="at">direction =</span> <span class="st">"both"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=436061
price ~ 1

          Df  Sum of Sq        RSS    AIC
+ carat    1 3.6137e+11 6.3607e+10 386168
+ color    6 1.3342e+10 4.1164e+11 435235
+ clarity  7 1.1972e+10 4.1301e+11 435324
+ table    1 6.8100e+09 4.1817e+11 435639
+ cut      4 5.2941e+09 4.1969e+11 435740
&lt;none&gt;                  4.2498e+11 436061
+ depth    1 2.8039e+06 4.2498e+11 436063

Step:  AIC=386167.8
price ~ carat

          Df  Sum of Sq        RSS    AIC
+ clarity  7 1.9137e+10 4.4469e+10 376779
+ color    6 6.4290e+09 5.7178e+10 383381
+ cut      4 2.8232e+09 6.0783e+10 384983
+ table    1 7.3987e+08 6.2867e+10 385862
+ depth    1 5.2659e+08 6.3080e+10 385951
&lt;none&gt;                  6.3607e+10 386168
- carat    1 3.6137e+11 4.2498e+11 436061

Step:  AIC=376779.3
price ~ carat + clarity

                Df  Sum of Sq        RSS    AIC
+ color          6 8.3042e+09 3.6165e+10 371361
+ carat:clarity  7 5.5857e+09 3.8884e+10 373267
+ cut            4 9.0782e+08 4.3562e+10 376245
+ table          1 2.1336e+08 4.4256e+10 376655
+ depth          1 1.7272e+08 4.4297e+10 376679
&lt;none&gt;                        4.4469e+10 376779
- clarity        7 1.9137e+10 6.3607e+10 386168
- carat          1 3.6854e+11 4.1301e+11 435324

Step:  AIC=371361.2
price ~ carat + clarity + color

                Df  Sum of Sq        RSS    AIC
+ carat:clarity  7 5.3993e+09 3.0766e+10 367128
+ cut            4 8.2532e+08 3.5340e+10 370763
+ table          1 2.4296e+08 3.5922e+10 371186
+ depth          1 7.6146e+07 3.6089e+10 371308
&lt;none&gt;                        3.6165e+10 371361
- color          6 8.3042e+09 4.4469e+10 376779
- clarity        7 2.1012e+10 5.7178e+10 383381
- carat          1 3.6325e+11 3.9942e+11 434457

Step:  AIC=367127.5
price ~ carat + clarity + color + carat:clarity

                Df  Sum of Sq        RSS    AIC
+ cut            4  852553680 2.9913e+10 366397
+ table          1  315613039 3.0450e+10 366859
+ depth          1   62770248 3.0703e+10 367076
&lt;none&gt;                        3.0766e+10 367128
- carat:clarity  7 5399342295 3.6165e+10 371361
- color          6 8117818803 3.8884e+10 373267

Step:  AIC=366397.3
price ~ carat + clarity + color + cut + carat:clarity

                Df  Sum of Sq        RSS    AIC
+ table          1   55887056 2.9857e+10 366350
&lt;none&gt;                        2.9913e+10 366397
+ depth          1     851633 2.9912e+10 366399
- cut            4  852553680 3.0766e+10 367128
- carat:clarity  7 5426571635 3.5340e+10 370763
- color          6 8042839625 3.7956e+10 372641

Step:  AIC=366350.2
price ~ carat + clarity + color + cut + table + carat:clarity

                Df  Sum of Sq        RSS    AIC
+ depth          1   19825582 2.9838e+10 366335
&lt;none&gt;                        2.9857e+10 366350
- table          1   55887056 2.9913e+10 366397
- cut            4  592827697 3.0450e+10 366859
- carat:clarity  7 5448503430 3.5306e+10 370739
- color          6 8064164279 3.7922e+10 372619

Step:  AIC=366334.7
price ~ carat + clarity + color + cut + table + depth + carat:clarity

                Df  Sum of Sq        RSS    AIC
&lt;none&gt;                        2.9838e+10 366335
- depth          1   19825582 2.9857e+10 366350
- table          1   74861004 2.9912e+10 366399
- cut            4  407342187 3.0245e+10 366683
- carat:clarity  7 5448175205 3.5286e+10 370726
- color          6 8013538464 3.7851e+10 372572</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stepwise_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ carat + clarity + color + cut + table + 
    depth + carat:clarity, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-8846.7  -646.6  -144.3   504.2  8152.2 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         820.289    478.651   1.714   0.0866 .  
carat             11700.715    119.138  98.212  &lt; 2e-16 ***
clarityVVS1         220.170     84.885   2.594   0.0095 ** 
clarityVVS2          87.744     80.966   1.084   0.2785    
clarityVS1          164.788     77.020   2.140   0.0324 *  
clarityVS2           -8.765     74.883  -0.117   0.9068    
claritySI1         -147.146     75.455  -1.950   0.0512 .  
claritySI2         -675.737     79.115  -8.541  &lt; 2e-16 ***
clarityI1          1552.534    146.747  10.580  &lt; 2e-16 ***
colorE             -177.769     24.258  -7.328 2.40e-13 ***
colorF             -289.658     24.559 -11.794  &lt; 2e-16 ***
colorG             -519.607     23.984 -21.665  &lt; 2e-16 ***
colorH             -928.199     25.654 -36.182  &lt; 2e-16 ***
colorI            -1450.775     28.625 -50.682  &lt; 2e-16 ***
colorJ            -2318.542     35.079 -66.094  &lt; 2e-16 ***
cutPremium          -97.605     19.660  -4.965 6.92e-07 ***
cutVery Good       -116.890     19.282  -6.062 1.36e-09 ***
cutGood            -303.008     27.526 -11.008  &lt; 2e-16 ***
cutFair            -813.793     45.873 -17.740  &lt; 2e-16 ***
table               -32.205      3.969  -8.114 5.10e-16 ***
depth               -22.882      5.480  -4.176 2.98e-05 ***
carat:clarityVVS1 -1032.086    145.668  -7.085 1.42e-12 ***
carat:clarityVVS2 -1257.669    133.231  -9.440  &lt; 2e-16 ***
carat:clarityVS1  -2236.415    125.433 -17.830  &lt; 2e-16 ***
carat:clarityVS2  -2446.445    123.044 -19.883  &lt; 2e-16 ***
carat:claritySI1  -3083.807    122.753 -25.122  &lt; 2e-16 ***
carat:claritySI2  -3422.767    123.077 -27.810  &lt; 2e-16 ***
carat:clarityI1   -7137.031    149.521 -47.733  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1066 on 26242 degrees of freedom
Multiple R-squared:  0.9298,    Adjusted R-squared:  0.9297 
F-statistic: 1.287e+04 on 27 and 26242 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Based on the EDA and due to computational cost, we only include 1 interaction term, namely ‘carat:clarity’ and assuming no interaction between the other covariates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(stepwise_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The Residuals vs Fitted plot does not show homoscedasticity. The Q-Q plot also suggests that the residuals do not really follow a normal distribution. Therefore, we need to address by applying log transform on the response variable (price) and one of the covariates (carat). # Results and Interpretation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate key metrics</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>rss <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">resid</span>(stepwise_model)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>tss <span class="ot">&lt;-</span> <span class="fu">sum</span>((data<span class="sc">$</span>price <span class="sc">-</span> <span class="fu">mean</span>(data<span class="sc">$</span>price))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (rss <span class="sc">/</span> tss)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>adjusted_r_squared <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> ((<span class="dv">1</span> <span class="sc">-</span> r_squared) <span class="sc">*</span> ((<span class="fu">nrow</span>(data) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> (<span class="fu">nrow</span>(data) <span class="sc">-</span> <span class="fu">length</span>(<span class="fu">coef</span>(stepwise_model)) <span class="sc">-</span> <span class="dv">1</span>)))</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary table</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>model_metrics <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Metric =</span> <span class="fu">c</span>(<span class="st">"R²"</span>, <span class="st">"Adjusted R²"</span>),</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value =</span> <span class="fu">c</span>(r_squared, adjusted_r_squared)</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_metrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Metric      Value
  &lt;chr&gt;       &lt;dbl&gt;
1 R²          0.930
2 Adjusted R² 0.930</code></pre>
</div>
</div>
</section>
<section id="log-transformation" class="level1">
<h1>Log Transformation</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>log_price <span class="ot">&lt;-</span> <span class="fu">log</span>(data<span class="sc">$</span>price) </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>log_carat <span class="ot">&lt;-</span> <span class="fu">log</span>(data<span class="sc">$</span>carat)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="co"># performing backward selection</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>log_transformed_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_price <span class="sc">~</span> log_carat <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity <span class="sc">+</span> table <span class="sc">+</span> depth <span class="sc">+</span> log_carat<span class="sc">:</span>clarity, <span class="at">data =</span> data)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_transformed_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_price ~ log_carat + cut + color + clarity + 
    table + depth + log_carat:clarity, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.73894 -0.08616 -0.00063  0.08301  1.46313 

Coefficients:
                        Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)            9.2549866  0.0597255  154.959  &lt; 2e-16 ***
log_carat              1.8763980  0.0095841  195.783  &lt; 2e-16 ***
cutPremium            -0.0212670  0.0024412   -8.712  &lt; 2e-16 ***
cutVery Good          -0.0431199  0.0023958  -17.998  &lt; 2e-16 ***
cutGood               -0.0779755  0.0034198  -22.801  &lt; 2e-16 ***
cutFair               -0.1537453  0.0056994  -26.976  &lt; 2e-16 ***
colorE                -0.0557291  0.0030145  -18.487  &lt; 2e-16 ***
colorF                -0.0939912  0.0030537  -30.779  &lt; 2e-16 ***
colorG                -0.1586006  0.0029815  -53.196  &lt; 2e-16 ***
colorH                -0.2503389  0.0031861  -78.573  &lt; 2e-16 ***
colorI                -0.3744722  0.0035433 -105.686  &lt; 2e-16 ***
colorJ                -0.5111972  0.0043372 -117.864  &lt; 2e-16 ***
clarityVVS1           -0.1057479  0.0110674   -9.555  &lt; 2e-16 ***
clarityVVS2           -0.1526922  0.0100702  -15.163  &lt; 2e-16 ***
clarityVS1            -0.2942064  0.0095386  -30.844  &lt; 2e-16 ***
clarityVS2            -0.3707328  0.0093873  -39.493  &lt; 2e-16 ***
claritySI1            -0.5095370  0.0093417  -54.544  &lt; 2e-16 ***
claritySI2            -0.6820053  0.0093623  -72.846  &lt; 2e-16 ***
clarityI1             -1.0804519  0.0118018  -91.550  &lt; 2e-16 ***
table                 -0.0008540  0.0004934   -1.731  0.08348 .  
depth                 -0.0013011  0.0006806   -1.912  0.05592 .  
log_carat:clarityVVS1 -0.0125769  0.0116118   -1.083  0.27876    
log_carat:clarityVVS2  0.0224515  0.0107734    2.084  0.03717 *  
log_carat:clarityVS1   0.0100679  0.0102727    0.980  0.32707    
log_carat:clarityVS2  -0.0006723  0.0100448   -0.067  0.94664    
log_carat:claritySI1   0.0259592  0.0100713    2.578  0.00996 ** 
log_carat:claritySI2   0.0055497  0.0103623    0.536  0.59227    
log_carat:clarityI1   -0.2387032  0.0179933  -13.266  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1324 on 26242 degrees of freedom
Multiple R-squared:  0.9831,    Adjusted R-squared:  0.9831 
F-statistic: 5.664e+04 on 27 and 26242 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># excluding table</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>log_transformed_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_price <span class="sc">~</span> log_carat <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity <span class="sc">+</span> depth <span class="sc">+</span> log_carat<span class="sc">:</span>clarity, <span class="at">data =</span> data)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_transformed_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_price ~ log_carat + cut + color + clarity + 
    depth + log_carat:clarity, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.73935 -0.08640 -0.00076  0.08298  1.46606 

Coefficients:
                        Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)            9.1767922  0.0390694  234.884  &lt; 2e-16 ***
log_carat              1.8759929  0.0095816  195.791  &lt; 2e-16 ***
cutPremium            -0.0233206  0.0021336  -10.930  &lt; 2e-16 ***
cutVery Good          -0.0448317  0.0021823  -20.544  &lt; 2e-16 ***
cutGood               -0.0805746  0.0030726  -26.224  &lt; 2e-16 ***
cutFair               -0.1575095  0.0052684  -29.897  &lt; 2e-16 ***
colorE                -0.0557929  0.0030144  -18.509  &lt; 2e-16 ***
colorF                -0.0939493  0.0030538  -30.765  &lt; 2e-16 ***
colorG                -0.1585699  0.0029815  -53.184  &lt; 2e-16 ***
colorH                -0.2502998  0.0031861  -78.560  &lt; 2e-16 ***
colorI                -0.3745157  0.0035433 -105.696  &lt; 2e-16 ***
colorJ                -0.5112250  0.0043373 -117.867  &lt; 2e-16 ***
clarityVVS1           -0.1056891  0.0110678   -9.549  &lt; 2e-16 ***
clarityVVS2           -0.1527463  0.0100705  -15.168  &lt; 2e-16 ***
clarityVS1            -0.2942627  0.0095389  -30.849  &lt; 2e-16 ***
clarityVS2            -0.3708475  0.0093874  -39.505  &lt; 2e-16 ***
claritySI1            -0.5097004  0.0093416  -54.563  &lt; 2e-16 ***
claritySI2            -0.6821421  0.0093623  -72.861  &lt; 2e-16 ***
clarityI1             -1.0808518  0.0117999  -91.598  &lt; 2e-16 ***
depth                 -0.0008092  0.0006184   -1.308  0.19073    
log_carat:clarityVVS1 -0.0122698  0.0116108   -1.057  0.29063    
log_carat:clarityVVS2  0.0226299  0.0107733    2.101  0.03569 *  
log_carat:clarityVS1   0.0102013  0.0102729    0.993  0.32070    
log_carat:clarityVS2  -0.0005337  0.0100448   -0.053  0.95763    
log_carat:claritySI1   0.0259920  0.0100716    2.581  0.00986 ** 
log_carat:claritySI2   0.0056159  0.0103627    0.542  0.58787    
log_carat:clarityI1   -0.2382233  0.0179919  -13.241  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1324 on 26243 degrees of freedom
Multiple R-squared:  0.9831,    Adjusted R-squared:  0.9831 
F-statistic: 5.881e+04 on 26 and 26243 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># excluding depth</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>log_transformed_model <span class="ot">&lt;-</span><span class="fu">lm</span>(log_price <span class="sc">~</span> log_carat <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity <span class="sc">+</span> log_carat<span class="sc">:</span>clarity, <span class="at">data =</span> data)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_transformed_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_price ~ log_carat + cut + color + clarity + 
    log_carat:clarity, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.74032 -0.08638 -0.00071  0.08311  1.47267 

Coefficients:
                        Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)            9.1271924  0.0094599  964.825   &lt;2e-16 ***
log_carat              1.8761372  0.0095811  195.817   &lt;2e-16 ***
cutPremium            -0.0229420  0.0021139  -10.853   &lt;2e-16 ***
cutVery Good          -0.0449152  0.0021814  -20.590   &lt;2e-16 ***
cutGood               -0.0810893  0.0030474  -26.610   &lt;2e-16 ***
cutFair               -0.1592576  0.0050963  -31.250   &lt;2e-16 ***
colorE                -0.0557636  0.0030144  -18.499   &lt;2e-16 ***
colorF                -0.0939317  0.0030538  -30.759   &lt;2e-16 ***
colorG                -0.1586500  0.0029809  -53.222   &lt;2e-16 ***
colorH                -0.2504149  0.0031849  -78.625   &lt;2e-16 ***
colorI                -0.3746555  0.0035418 -105.783   &lt;2e-16 ***
colorJ                -0.5113655  0.0043360 -117.934   &lt;2e-16 ***
clarityVVS1           -0.1059745  0.0110658   -9.577   &lt;2e-16 ***
clarityVVS2           -0.1529754  0.0100692  -15.192   &lt;2e-16 ***
clarityVS1            -0.2944764  0.0095376  -30.875   &lt;2e-16 ***
clarityVS2            -0.3711392  0.0093849  -39.546   &lt;2e-16 ***
claritySI1            -0.5100598  0.0093377  -54.624   &lt;2e-16 ***
claritySI2            -0.6824368  0.0093597  -72.912   &lt;2e-16 ***
clarityI1             -1.0814596  0.0117910  -91.719   &lt;2e-16 ***
log_carat:clarityVVS1 -0.0124857  0.0116098   -1.075   0.2822    
log_carat:clarityVVS2  0.0224939  0.0107730    2.088   0.0368 *  
log_carat:clarityVS1   0.0100984  0.0102727    0.983   0.3256    
log_carat:clarityVS2  -0.0006396  0.0100447   -0.064   0.9492    
log_carat:claritySI1   0.0259102  0.0100716    2.573   0.0101 *  
log_carat:claritySI2   0.0054672  0.0103622    0.528   0.5978    
log_carat:clarityI1   -0.2384572  0.0179912  -13.254   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1324 on 26244 degrees of freedom
Multiple R-squared:  0.9831,    Adjusted R-squared:  0.9831 
F-statistic: 6.116e+04 on 25 and 26244 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Based on the summary above, after applying log transformation on ‘carat’ and dropping ‘depth’, and ‘table’ we achieved better R^2 and adjusted R^2. This simpler model is easier for interpretation and has the same adjusted R^2 as the larger models. Since the interaction between some clarity levels and carat are significant, we have chosen to include it in the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(log_transformed_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now, the residuals vs fitted plot suggests heteroscedasticity is less of a concern as the points are now centering around zero and have constant variance. However, another possible concern is that of a slight curve in the residuals, which might suggest a non-linear relationship. We have already included one non linear relationship - that of the interaction term, however it may not be enough.</p>
<p>The Q-Q plot looks better than the previous model’s, although the deviations at the end suggest a distribution with heavier tails rather than a normal distribution. Alternatively, it may also suggest the presence of outliers, which is present as analyzed previously.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Trying a cubic relationship between log(carat) and log(price)</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>cubic_relation <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_price <span class="sc">~</span> log_carat <span class="sc">+</span> <span class="fu">I</span>(log_carat<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(log_carat<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity <span class="sc">+</span> </span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    log_carat<span class="sc">:</span>clarity, <span class="at">data =</span> data)</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cubic_relation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_price ~ log_carat + I(log_carat^2) + I(log_carat^3) + 
    cut + color + clarity + log_carat:clarity, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.61629 -0.08208 -0.00126  0.07995  1.38984 

Coefficients:
                       Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)            9.165846   0.008977 1021.076  &lt; 2e-16 ***
log_carat              2.018355   0.009663  208.871  &lt; 2e-16 ***
I(log_carat^2)        -0.123066   0.004260  -28.892  &lt; 2e-16 ***
I(log_carat^3)        -0.198536   0.003804  -52.194  &lt; 2e-16 ***
cutPremium            -0.028673   0.002003  -14.317  &lt; 2e-16 ***
cutVery Good          -0.054433   0.002071  -26.286  &lt; 2e-16 ***
cutGood               -0.086089   0.002886  -29.834  &lt; 2e-16 ***
cutFair               -0.159539   0.004823  -33.077  &lt; 2e-16 ***
colorE                -0.057196   0.002852  -20.056  &lt; 2e-16 ***
colorF                -0.097975   0.002891  -33.894  &lt; 2e-16 ***
colorG                -0.162092   0.002820  -57.474  &lt; 2e-16 ***
colorH                -0.257782   0.003016  -85.459  &lt; 2e-16 ***
colorI                -0.377716   0.003361 -112.374  &lt; 2e-16 ***
colorJ                -0.510974   0.004123 -123.928  &lt; 2e-16 ***
clarityVVS1           -0.092345   0.010470   -8.820  &lt; 2e-16 ***
clarityVVS2           -0.154852   0.009524  -16.259  &lt; 2e-16 ***
clarityVS1            -0.306725   0.009030  -33.969  &lt; 2e-16 ***
clarityVS2            -0.384145   0.008889  -43.215  &lt; 2e-16 ***
claritySI1            -0.522590   0.008845  -59.083  &lt; 2e-16 ***
claritySI2            -0.692898   0.008877  -78.057  &lt; 2e-16 ***
clarityI1             -1.096351   0.011167  -98.176  &lt; 2e-16 ***
log_carat:clarityVVS1  0.009683   0.010989    0.881  0.37825    
log_carat:clarityVVS2  0.029296   0.010191    2.875  0.00405 ** 
log_carat:clarityVS1  -0.014919   0.009743   -1.531  0.12575    
log_carat:clarityVS2  -0.027935   0.009539   -2.929  0.00341 ** 
log_carat:claritySI1  -0.013727   0.009603   -1.429  0.15291    
log_carat:claritySI2  -0.021660   0.010030   -2.160  0.03081 *  
log_carat:clarityI1   -0.186538   0.017494  -10.663  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1253 on 26242 degrees of freedom
Multiple R-squared:  0.9849,    Adjusted R-squared:  0.9849 
F-statistic: 6.341e+04 on 27 and 26242 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> cubic_relation<span class="sc">$</span>residuals, <span class="at">x =</span> cubic_relation<span class="sc">$</span>fitted.values, <span class="at">main =</span> <span class="st">"Residual Plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Although the above cubic model has a higher adjusted R^2 : 0.9849 vs the old model : 0.9831, the additional complexity of the cubic model is not justified by the small increase of 0.0018 in R^2. The residual plot also doesn’t look much better than the previous model. So even though the cubic log(carat) value is significant in the summary, we have decided to choose the more simplistic model as we have already captured some non-linearity with our interaction term between clarity and log_carat.</p>
<p>Our final model for this section is $ log(price) = _0 + _1*log(carat) + _2*cut + _3*color + _4*clarity + _5<em>log(carat)</em>clarity $</p>
</section>
<section id="regression-analysis-using-pca-to-address-multicollinearity" class="level1">
<h1>Regression Analysis Using PCA To Address Multicollinearity</h1>
<p>We will now compare the above method of dropping the volume variable with the PCA method.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting carat and volume covariates into their own dataframe:</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> path, <span class="at">col_names =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">drop_na</span>(depth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
Rows: 26967 Columns: 11
── Column specification
──────────────────────────────────────────────────────── Delimiter: "," chr
(3): cut, color, clarity dbl (8): ...1, carat, depth, table, x, y, z, price
ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
Specify the column types or set `show_col_types = FALSE` to quiet this message.
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>volume <span class="ot">&lt;-</span> data<span class="sc">$</span>x <span class="sc">*</span> data<span class="sc">$</span>y <span class="sc">*</span> data<span class="sc">$</span>z</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>subset_data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">select</span>(volume, carat)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(subset_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  volume carat
   &lt;dbl&gt; &lt;dbl&gt;
1   48.7  0.3 
2   53.2  0.33
3  140.   0.9 
4   68.5  0.42
5   51.1  0.31
6  167.   1.02</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Applying PCA on standardized carat and volume</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>pc_car_vol <span class="ot">&lt;-</span> <span class="fu">princomp</span>(subset_data, <span class="at">cor =</span> T)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pc_car_vol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The above graph shows that most of the variance is captured by the first component. The code cell below calculates that around 98% of variance is captured by the first component. Therefore, we can now regress our model on only the first component as the second isn’t needed given that it is only capturing around 2% of variation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>lambdas <span class="ot">&lt;-</span> pc_car_vol<span class="sc">$</span>sdev<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Computing variation proportion captured by first X principal components</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>( <span class="fu">sum</span>(lambdas[<span class="dv">1</span>]) <span class="sc">/</span> <span class="fu">sum</span>(lambdas) )  <span class="co"># First PC</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9801025</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>( <span class="fu">sum</span>(lambdas[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]) <span class="sc">/</span> <span class="fu">sum</span>(lambdas) )  <span class="co"># First two PCs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>pcr_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(price) <span class="sc">~</span> (pc_car_vol<span class="sc">$</span>scores[,<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">I</span>(pc_car_vol<span class="sc">$</span>scores[,<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(pc_car_vol<span class="sc">$</span>scores[,<span class="dv">1</span>]<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity <span class="sc">+</span> clarity<span class="sc">:</span>pc_car_vol<span class="sc">$</span>scores[,<span class="dv">1</span>] <span class="sc">+</span> depth <span class="sc">+</span> table, <span class="at">data =</span> data)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pcr_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(price) ~ (pc_car_vol$scores[, 1]) + I(pc_car_vol$scores[, 
    1]^2) + I(pc_car_vol$scores[, 1]^3) + cut + color + clarity + 
    clarity:pc_car_vol$scores[, 1] + depth + table, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.8328 -0.0943  0.0062  0.0970  3.2388 

Coefficients:
                                     Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)                         6.945e+00  7.047e-02   98.543  &lt; 2e-16 ***
pc_car_vol$scores[, 1]              1.010e+00  4.898e-03  206.248  &lt; 2e-16 ***
I(pc_car_vol$scores[, 1]^2)        -1.309e-01  4.711e-04 -277.860  &lt; 2e-16 ***
I(pc_car_vol$scores[, 1]^3)         3.062e-03  1.338e-05  228.813  &lt; 2e-16 ***
cutGood                             5.304e-02  6.405e-03    8.281  &lt; 2e-16 ***
cutIdeal                            1.273e-01  6.406e-03   19.867  &lt; 2e-16 ***
cutPremium                          9.542e-02  6.161e-03   15.486  &lt; 2e-16 ***
cutVery Good                        7.355e-02  6.156e-03   11.947  &lt; 2e-16 ***
colorE                             -5.712e-02  3.386e-03  -16.868  &lt; 2e-16 ***
colorF                             -9.663e-02  3.432e-03  -28.155  &lt; 2e-16 ***
colorG                             -1.634e-01  3.351e-03  -48.760  &lt; 2e-16 ***
colorH                             -2.667e-01  3.582e-03  -74.458  &lt; 2e-16 ***
colorI                             -3.825e-01  3.996e-03  -95.711  &lt; 2e-16 ***
colorJ                             -5.112e-01  4.903e-03 -104.263  &lt; 2e-16 ***
clarityIF                           1.140e+00  1.237e-02   92.165  &lt; 2e-16 ***
claritySI1                          6.447e-01  1.027e-02   62.770  &lt; 2e-16 ***
claritySI2                          4.788e-01  1.036e-02   46.241  &lt; 2e-16 ***
clarityVS1                          8.460e-01  1.041e-02   81.296  &lt; 2e-16 ***
clarityVS2                          7.767e-01  1.031e-02   75.328  &lt; 2e-16 ***
clarityVVS1                         1.049e+00  1.127e-02   93.070  &lt; 2e-16 ***
clarityVVS2                         9.739e-01  1.069e-02   91.103  &lt; 2e-16 ***
depth                               4.106e-03  7.648e-04    5.370 7.96e-08 ***
table                               2.760e-03  5.541e-04    4.982 6.34e-07 ***
pc_car_vol$scores[, 1]:clarityIF   -4.775e-02  7.524e-03   -6.347 2.24e-10 ***
pc_car_vol$scores[, 1]:claritySI1  -7.862e-02  4.859e-03  -16.180  &lt; 2e-16 ***
pc_car_vol$scores[, 1]:claritySI2  -7.388e-02  4.722e-03  -15.646  &lt; 2e-16 ***
pc_car_vol$scores[, 1]:clarityVS1  -7.834e-02  5.110e-03  -15.330  &lt; 2e-16 ***
pc_car_vol$scores[, 1]:clarityVS2  -8.039e-02  4.936e-03  -16.284  &lt; 2e-16 ***
pc_car_vol$scores[, 1]:clarityVVS1 -4.064e-02  6.371e-03   -6.379 1.81e-10 ***
pc_car_vol$scores[, 1]:clarityVVS2 -4.393e-02  5.664e-03   -7.756 9.08e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1488 on 26240 degrees of freedom
Multiple R-squared:  0.9787,    Adjusted R-squared:  0.9787 
F-statistic: 4.157e+04 on 29 and 26240 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> pcr_model<span class="sc">$</span>residuals, <span class="at">x =</span> pcr_model<span class="sc">$</span>fitted.values, <span class="at">main =</span> <span class="st">"Residual Plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(pcr_model<span class="sc">$</span>residuals, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(pcr_model<span class="sc">$</span>residuals, <span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project_1_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The residual plot and qq-plot show similar concerns as the model fitted before. Namely, the qq plot’s curve at the end suggests the presence of outliers or heavier tailed distribution of the residuals rather than a normal distribution. The residual plot also suggests the presence of some outliers. There is not as much concern for heteroscedasticity.</p>
<p>As seen above, the pca model required a cubic first principal component and two more covariates: namely depth and table, to be approximately the same adjusted R^2 as the previous method’s model. The previous model’s adjusted R^2 was 0.9831 and the pcr model’s adjusted R^2 is 0.9787. This is a difference of 0.0044, which is rather insignificant. This suggests that while both method perform similarly in explaining the variation in the data, the first model (created by dropping the volume covariate), is better as it is simpler to interpret. This choice is in line with the principle of parsimony. Therefore, we conclude the better model for this data is the model created by dropping the volume variable:</p>
<p>$ log(price) = _0 + _1*log(carat) + _2*cut + _3*color + _4*clarity + _5<em>log(carat)</em>clarity $</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>